### ISSUE TITLE
Move depth property

### ISSUE THREAD

**Issue by Tempus** [Trevoke/SGFParser#12]
The SGF format is move independent, but human logic is not. A move depth property shoudl be available for each node, specifying it’s depth from root. This is analogous to ‘move number’, as it is equivalent to the position if the node from the root (move 0). 

Adding bonus properties like slices, or enumerations based on these would be delicious, delicious frosting on the cake of usability.

**Comment by Trevoke** [comment]
Depth has been implemented.

Slicing has been at least partially implemented.
