### ISSUE TITLE
Parsing bad(?) sgf

### ISSUE THREAD

**Issue by jphager2** [Trevoke/SGFParser#23]
Hi,

I'm using SgfParser (which is awesome, by the way) to parse tsumego from goproblems.com.

I guess this isn't a problem with SgfParser as such, but some of the sgf on goproblems has a format that doesn't parse correctly with SGF::Parser.new.parse.  
(e.g. when it starts like "(;AB[ee]AB[ef]AB[ff]AW[ed]AW[dd]...")

In this case it just lists one AB/AW node (the last occurring), so in the example above AB=>'ff', AW=>'dd'.

For me I just validated it using some really ugly code (the source is on github, called gotasku), but maybe this case is a big enough deal to incorporate into the SgfParser.

Here is an example from goproblems:

goproblems.com/10000
```
(;AB[bq]AB[cq]AB[dp]AB[ep]AB[fp]AB[gp]AB[co]AB[hq]AB[iq]AB[jr]AB[gr]AW[gq]AW[fq]AW[eq]AW[dq]AW[cr]AW[hr]AW[hs]C[black to kill]AP[goproblems](;B[er](;W[dr]C[CHOICE](;B[fr];W[es](;B[br](;W[cs];B[bs]C[RIGHT])(;W[fs];B[cs]C[RIGHT]))(;B[is];W[fs])(;B[ir];W[fs])(;B[cs];W[br]))(;B[br];W[fr]))(;W[fr];B[dr]C[RIGHT]))(;B[fr];W[er](;B[es];W[dr](;B[br];W[fs];B[cs];W[gs])(;B[fs];W[gs])(;B[ds];W[br])(;B[cs];W[br]))(;B[ds];W[es](;B[cs];W[br])(;B[br];W[cs])))(;B[fs];W[es](;B[er];W[dr];B[ds];W[fr])(;B[is];W[fr])(;B[fr];W[er]))(;B[gs];W[fs])(;B[br];W[ds](;B[fr];W[er])(;B[er];W[fr]))(;B[es];W[er](;B[fs];W[gs];B[cs];W[fr])(;B[cs];W[fs])(;B[fr])))
```

**Comment by Trevoke** [comment]
At least this use case is handled. Closing.
