### ISSUE TITLE
Use parser as an editor

### ISSUE THREAD

**Issue by kokolegorille** [Trevoke/SGFParser#25]
Hello, 
I tried to use the parser as an sgf editor.
I opened a sgf file, parsed into a tree, took the first game, current_node and then edited its properties.
But then when I tried to save back the tree as sgf, the current_node properties were back to old values.
Is there a way to use a parsed tree, modify some nodes and then save it back to a file?
Thanks in advance

Here is a sample code

require 'sgf'
parser = SGF::Parser.new
tree = parser.parse <filename>
tree.games.first.current_node[:EV] = "whatever"
tree.save <new_filename>
(does not work, new_filename does not contains changed property)

**Comment by Trevoke** [comment]
Wow. That counts as a bug. Wrote a test to verify that it absolutely does not work. I am mortified. I will fix it.

**Comment by Trevoke** [comment]
Found it and fixed it. Also uncovered another bug (see #26) while I was at it.

Have not pushed the changes to rubygems yet (erm, have to remember credentials.. And I'm on a Windows box right now), but master is working, you can use 1484ed1b5268a9bc17c34e47cce86b6f6d9d88b5 for now.

**Comment by kokolegorille** [comment]
Thank You very much for your support, it is now working.
I have been using your parser for sanitizing games from Haylee's Live Go,
found at http://hajin.nl/games.php
I extracted them and edited them with your parser.

2016-04-20 6:00 GMT+02:00 Aldric Giacomoni <notifications@github.com>:
